"""Build data/search-index.json for the client-side header search (Phase 5, WS2).

Emits a flat list of { title, url, kind, keywords } covering every static page
(topics, places, industries), all 14 metro report pages, and all 159 counties.
County entries currently point at their metro report (if the county is in a GA
MSA) or the /counties/ heat map otherwise — repoint to /counties/<slug>/ once
the WS4 county profiles exist.

Pure-static, deterministic output (sorted), so an unchanged run produces no git
diff. Run in CI after the data refresh, or locally before a deploy:

    python3 scripts/build_search_index.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = DATA / "search-index.json"


def slugify(name: str) -> str:
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", name.lower().replace("&", "and"))).strip("-")


# Static pages — title, url, kind, search keywords/synonyms.
STATIC = [
    ("Georgia Economics — home", "/", "Page", "georgia state economy overview dashboard"),
    ("Counties", "/counties/", "Place", "county heat map unemployment 159 laus"),
    ("Metros", "/msa/", "Place", "metro msa metropolitan compare dashboard"),
    ("Population & Growth", "/population/", "Topic", "population growth migration census pep age race peers"),
    ("Labor Market", "/labor/", "Topic", "labor jobs employment unemployment payrolls nonfarm bls"),
    ("Housing", "/housing/", "Topic", "housing home prices fhfa affordability permits rent ownership"),
    ("State GDP", "/gdp/", "Topic", "gdp output economy per capita sectors bea"),
    ("Migration", "/migration/", "Topic", "migration movers domestic international irs soi inflow outflow"),
    ("Inflation", "/inflation/", "Topic", "inflation cpi prices gas gasoline atlanta south real wages"),
    ("Economic Outlook", "/outlook/", "Topic", "outlook forecast business cycle index recession projection"),
    ("Agriculture", "/industries/agriculture/", "Industry", "agriculture farm broilers peanuts pecans cotton blueberries usda nass"),
    ("Automotive & EV", "/industries/automotive/", "Industry", "automotive ev electric vehicle kia hyundai metaplant suppliers"),
    ("Data Centers", "/industries/data-centers/", "Industry", "data centers megawatts capacity georgia power hyperscale"),
    ("Film Industry", "/industries/film/", "Industry", "film movie production spend motion picture studios"),
    ("Trade & Logistics", "/trade/", "Industry", "trade logistics port savannah brunswick exports cargo teu"),
    ("Directory", "/directory/", "Page", "directory index sitemap all pages"),
    ("About", "/about/", "Page", "about methodology sources data"),
]


def main() -> int:
    items = [{"title": t, "url": u, "kind": k, "keywords": kw} for (t, u, k, kw) in STATIC]

    # Metros (from the MSA→county map).
    msa_counties = json.loads((DATA / "ga_msa_counties.json").read_text())["msas"]
    fips_to_metro = {}
    for cbsa, m in msa_counties.items():
        slug = slugify(m["short_name"])
        items.append({
            "title": f"{m['short_name']} metro",
            "url": f"/msa/{slug}/",
            "kind": "Metro",
            "keywords": f"{m['full_name']} msa metropolitan cbsa {cbsa}",
        })
        for f in m.get("counties", []):
            fips_to_metro[f] = slug

    # Counties (159) — each links to its own profile page (/counties/<slug>/),
    # generated by scripts/generate_county_pages.py (WS4).
    pts = json.loads((DATA / "counties.json").read_text())["frames"][-1]["points"]
    for p in pts:
        fips, nm = p["fips"], p["label"]
        metro_kw = f" {fips_to_metro[fips]} metro" if fips in fips_to_metro else ""
        items.append({
            "title": f"{nm} County",
            "url": f"/counties/{slugify(nm)}/",
            "kind": "County",
            "keywords": f"{nm.lower()} county fips {fips}{metro_kw}",
        })

    items.sort(key=lambda it: (it["kind"], it["title"]))
    payload = {"_note": "Generated by scripts/build_search_index.py — do not edit by hand.",
               "count": len(items), "items": items}
    OUT.write_text(json.dumps(payload, ensure_ascii=False, indent=1) + "\n")
    print(f"build_search_index: wrote {len(items)} items -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
