"""Generate REPORT_STATUS_MATRIX.md — a per-metro x per-section QA grid.

Reads every data/msa_reports/<slug>.json, pulls its `section_status` map, and
writes a markdown matrix (sections down the side, the 14 metros across the top)
so you can see at a glance which sections are live / partial / stale / pending /
failed for each metro. Run after a data refresh:

    python3 scripts/build_report_status_matrix.py

Pure stdlib; deterministic (sections and metros in fixed order), so re-running
without a data change produces no diff.
"""

from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(Path(__file__).parent))
from _ga_msas import GA_MSAS  # noqa: E402

JSON_DIR = ROOT / "data" / "msa_reports"
OUT = ROOT / "REPORT_STATUS_MATRIX.md"

# Metros across the top, largest first.
_METROS = sorted(GA_MSAS, key=lambda r: -r[3])

# Symbol per status.
SYM = {
    "live": "✓",
    "partial": "◐",
    "seed": "◐",
    "stale": "~",
    "pending": "·",
    "failed": "✗",
    "missing": "—",
}

# Preferred section display order (data sections then modeling). Any section not
# listed here is appended alphabetically so new sections never silently vanish.
SECTION_ORDER = [
    "ces_employment", "ces_by_supersector", "laus_unemployment", "fhfa_hpi",
    "census_pep", "census_acs_demographics", "bea_gmp", "bea_personal_income",
    "qcew_industry_shares", "qcew_yoy_changes", "qcew_3digit", "health_check",
    "census_bps_permits", "ita_msa_exports", "irs_soi_migration", "epa_air_quality",
    "school_finance", "acs_age_structure", "acs_affordability", "census_net_migration",
    "acs_housing_characteristics", "acs_block_group_income", "entrepreneurship",
    "major_employers",
    # modeling
    "business_cycle_index", "forecast_arima", "vitality", "quality_of_life",
    "housing_valuation", "business_costs", "industrial_diversity",
    "housing_affordability", "credit_score",
]


def _load():
    data = {}
    for cbsa, short, full, pop in _METROS:
        slug = short.lower().replace(" ", "-")
        path = JSON_DIR / f"{slug}.json"
        if path.exists():
            try:
                data[cbsa] = json.loads(path.read_text())
            except Exception as e:
                print(f"  WARN: {slug}.json unreadable: {e}", file=sys.stderr)
    return data


def build():
    data = _load()
    if not data:
        raise SystemExit("No metro JSONs found.")

    # Collect the full set of sections seen, ordered.
    seen = set()
    for d in data.values():
        seen.update((d.get("section_status") or {}).keys())
    sections = [s for s in SECTION_ORDER if s in seen]
    sections += sorted(s for s in seen if s not in SECTION_ORDER)

    as_of = max((str(d.get("as_of", "")) for d in data.values()), default="")
    short_by_cbsa = {cbsa: short for cbsa, short, _f, _p in _METROS}

    lines = []
    lines.append("# Metro Economic Profile — 14-MSA Status Matrix")
    lines.append("")
    lines.append("> Auto-generated by `scripts/build_report_status_matrix.py` from each "
                 "metro's `section_status`. Do not edit by hand. Companion to the "
                 "curated `REPORT_STATUS.md`.")
    lines.append("")
    lines.append(f"**Data as of:** {as_of} &middot; **Metros:** {len(data)} of {len(_METROS)} "
                 f"&middot; **Sections tracked:** {len(sections)}")
    lines.append("")
    lines.append("**Legend:** ✓ live &middot; ◐ partial/representative &middot; ~ stale "
                 "(kept prior on transient failure) &middot; · pending &middot; ✗ failed "
                 "&middot; — missing")
    lines.append("")

    # Header row
    cols = [short_by_cbsa[cbsa] for cbsa, *_ in _METROS if cbsa in data]
    cbsas = [cbsa for cbsa, *_ in _METROS if cbsa in data]
    lines.append("| Section | " + " | ".join(cols) + " |")
    lines.append("|" + "---|" * (len(cols) + 1))

    # Per-section rows
    for sec in sections:
        cells = []
        for cbsa in cbsas:
            st = (data[cbsa].get("section_status") or {}).get(sec, "missing")
            cells.append(SYM.get(st, st))
        lines.append(f"| `{sec}` | " + " | ".join(cells) + " |")

    # Summary counts per metro
    lines.append("")
    lines.append("## Per-metro totals")
    lines.append("")
    lines.append("| Metro | live | partial | stale | pending | failed |")
    lines.append("|---|---|---|---|---|---|")
    for cbsa in cbsas:
        statuses = list((data[cbsa].get("section_status") or {}).values())
        def n(*keys):
            return sum(1 for v in statuses if v in keys)
        lines.append(f"| {short_by_cbsa[cbsa]} | {n('live')} | {n('partial','seed')} | "
                     f"{n('stale')} | {n('pending')} | {n('failed')} |")

    lines.append("")
    lines.append(f"_Generated {date.today().isoformat()}._")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"  wrote {OUT.relative_to(ROOT)}  ({len(sections)} sections x {len(cols)} metros)")


if __name__ == "__main__":
    build()
