"""Build data/scorecard.json — the statewide "Economy at a glance" rollup (Phase 5, WS5).

Pulls one headline KPI from each topic's JSON into a single small file the home
page renders as a card strip (GE.scorecard in assets/app.js). Values are
formatted here so the renderer stays dumb. Deterministic output, so an unchanged
run produces no git diff. Run in CI after the topic JSONs refresh.

  trend: "good" | "bad" | "neutral"  → drives the delta colour (teal / coral / grey).

Usage:  python3 scripts/build_scorecard.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"


def _load(name):
    return json.loads((DATA / f"{name}.json").read_text())


def main() -> int:
    labor = _load("labor")["kpis"]
    house = _load("housing")["kpis"]
    gdp = _load("gdp")["kpis"]
    infl = _load("inflation")["kpis"]
    pop = _load("population")["kpis"]
    out = _load("outlook")["kpis"]

    pop_latest = pop["population_latest"]
    base_year = pop["latest_year"] - 5

    cards = [
        {
            "topic": "Labor", "href": "/labor/", "label": "Unemployment",
            "value": f"{labor['unemployment_rate_latest']:.1f}%",
            "delta": f"{labor['unemployment_rate_yoy_delta']:+.1f} pp YoY",
            # rising unemployment is bad; falling is good
            "trend": "bad" if labor["unemployment_rate_yoy_delta"] > 0 else ("good" if labor["unemployment_rate_yoy_delta"] < 0 else "neutral"),
        },
        {
            "topic": "Population", "href": "/population/", "label": "Population",
            "value": f"{pop_latest/1e6:.1f}M",
            "delta": f"+{pop['growth_pct_5yr']:.1f}% since {base_year}",
            "trend": "good" if pop["growth_pct_5yr"] >= 0 else "bad",
        },
        {
            "topic": "GDP", "href": "/gdp/", "label": "GDP per capita",
            "value": f"${gdp['ga_gdp_per_capita']:,}",
            "delta": f"{gdp['ga_real_gdp_yoy']:+.1f}% real GDP YoY",
            "trend": "good" if gdp["ga_real_gdp_yoy"] >= 0 else "bad",
        },
        {
            "topic": "Housing", "href": "/housing/", "label": "Home prices",
            "value": f"{house['ga_home_price_yoy']:+.1f}%",
            "delta": "FHFA HPI, YoY",
            "trend": "neutral",
        },
        {
            "topic": "Inflation", "href": "/inflation/", "label": "Inflation (South)",
            "value": f"{infl['headline_yoy_south']:+.1f}%",
            "delta": f"U.S. {infl['headline_yoy_us']:.1f}%",
            # above the Fed's ~2% target reads as bad
            "trend": "bad" if infl["headline_yoy_south"] > 2.5 else "neutral",
        },
        {
            "topic": "Migration", "href": "/migration/", "label": "Net migration",
            "value": f"+{pop['net_mig_latest']:,}",
            "delta": "domestic + international, yr",
            "trend": "good" if pop["net_mig_latest"] >= 0 else "bad",
        },
        {
            "topic": "Outlook", "href": "/outlook/", "label": "Business cycle",
            "value": out["cycle_direction"].title(),
            "delta": f"{out['cycle_vs_peak']:+.1f}% vs peak",
            "trend": "good" if str(out["cycle_direction"]).lower() in ("expanding", "recovering") else ("bad" if str(out["cycle_direction"]).lower() in ("contracting", "slowing") else "neutral"),
        },
    ]

    payload = {
        "_note": "Statewide headline KPIs for the home-page scorecard; generated by scripts/build_scorecard.py.",
        "as_of": {
            "labor": _load("labor").get("latest_label"),
            "gdp": _load("gdp").get("latest_label"),
            "inflation": infl.get("latest_month_south"),
        },
        "cards": cards,
    }
    (DATA / "scorecard.json").write_text(json.dumps(payload, ensure_ascii=False, indent=1) + "\n")
    print(f"build_scorecard: wrote {len(cards)} cards -> data/scorecard.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
